- hosts: all


  ###
  # Tasks
  ###
  tasks:


    ###
    # Vars
    ###
    - name: Load vars from vars directory
      include_vars: vars/myConfig.yml
      sudo: true


    ###################
    # Hostname
    ###################
    - name: Update Hosts file with hostname
      lineinfile: dest=/etc/hosts line="{{ publicIpAddress }} {{ hostname }}" backup=yes
      sudo: true
    - name: Update hostname to {{ hostname }}
      hostname: name={{ hostname }}
      sudo: true


    ###
    # Update APT
    ###
    - name: Update APT
      apt: update_cache=yes
      sudo: true


    ###
    # Time management
    ###
    - name: Install NTP (and update apt cache for the first install)
      apt: name={{ item }} state=latest
           update_cache=yes
      with_items:
        - ntp
        - tzdata
      sudo: true
    - name: Set local timezone
      copy: content={{ timezone }}
            dest=/etc/timezone
      sudo: true
    - name: Start the ntp service
      service: name=ntp state=started enabled=true
      sudo: true


    ###
    # Add skel for all users
    ###
    - name: Add zshrc
      template: src={{ rootPath }}/skel/etc/skel/.zshrc.j2 dest=/etc/skel/.zshrc owner=root group=root
      sudo: true


    ###
    # MISC Tools
    ###
    - name: Install MISC tools
      apt: name={{ item }} state=latest
      with_items:
        - language-pack-fr
        - dnsutils
        - iftop
        - smartmontools
        - iptraf
        - sysstat
        - vim
        - htop
        - git-core
        - curl
        - acl
        - htop
        - tig
        - tmux
        - screen
        - zsh
        - ncdu
        - ifstat
        - build-essential
        - openssh-client
        - imagemagick
        - ncdu
        - tree
      sudo: true


    ###
    # Create SSH user group
    ###
    - name: Create group sshuser
      group: name=sshuser state=present
      sudo: true
    - name: Create group sshuserpwd
      group: name=sshuserpwd state=present
      sudo: true
    - name: Create group sshuserkey
      group: name=sshuserkey state=present
      sudo: true


    ###
    # User Management
    ###
    - name: Add /usr/local/scripts directory
      file: path=/usr/local/scripts state=directory owner=root group=root
      sudo: true
    - name: Add login script
      template: src={{ rootPath }}/skel/usr/local/scripts/loginNotification.sh.j2 dest=/usr/local/scripts/loginNotification.sh owner=root group=root
      sudo: true
    - name: Change shell for current user
      shell: chsh -s /bin/zsh
      sudo: true
    - name: Create group {{ user }}
      group: name={{ user }} state=present
      sudo: true
    - name: Create user {{ user }}
      user: name={{ user }}
            comment="{{ user }} user"
            shell=/bin/zsh
            groups=sudo,adm,sshuser,sshuserpwd,{{ user }}
      sudo: true
    - name: Set up authorized_keys for {{ user }}
      authorized_key: user={{ user }}
                      key="{{ lookup('file', 'vars/mySSHPublicKey.pub') }}"
      sudo: true
    - name: Add SSH directory
      file: path=/home/{{ user }}/.ssh/ state=directory owner={{ user }} group={{ user }} mode=0755
      sudo: true
    - name: Add GithHub SSH private key for {{ user }}
      copy: src={{ rootPath }}/vars/myGitHubUserMachineUserKey dest=/home/{{ user }}/.ssh/myGitHubMachineUserKey owner={{ user }} group={{ user }} mode=0600
      sudo: true
    - name: Add GithHub SSH public key for {{ user }}
      copy: src={{ rootPath }}/vars/myGitHubUserMachineUserKey.pub dest=/home/{{ user }}/.ssh/myGitHubMachineUserKey.pub owner={{ user }} group={{ user }} mode=0644
      sudo: true
    - name: Add GitHub SSH config for {{ user }}
      copy: src={{ rootPath }}/skel/home/myuser/.ssh/config dest=/home/{{ user }}/.ssh/config owner={{ user }} group={{ user }} mode=0644 backup=yes
      sudo: true


    ###
    # Security Tools
    ###
    - name: Install Security tools
      apt: name={{ item }} state=latest
      with_items:
        - fail2ban
      sudo: true
    - name: Disable Root login (useless on Ubuntu but just in case ;-)
      lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin no' backup=yes
      sudo: true
    - name: Some security optim
      lineinfile: dest=/etc/ssh/sshd_config line="Match User {{ user }}" backup=yes
      sudo: true
    - name: Some security optim
      lineinfile: dest=/etc/ssh/sshd_config line="    PasswordAuthentication yes" backup=yes
      sudo: true
    - name: Some security optim
      lineinfile: dest=/etc/ssh/sshd_config line="Match User ubuntu" backup=yes
      sudo: true
    - name: Some security optim
      lineinfile: dest=/etc/ssh/sshd_config line="    PasswordAuthentication no" backup=yes
      sudo: true
    - name: Restart SSHd
      service: name=ssh state=reloaded
      sudo: true


    ###
    # Supervisor
    ###
    - name: Install Supervisor
      apt: name=supervisor state=latest
      sudo: true
    - name: Start supervisor service
      service: name=supervisor state=started enabled=true
      sudo: true


    ###
    # Install Python+PIP
    ###
    - name: Install Python+PIP
      apt: name={{ item }} state=latest
      with_items:
        - python
        - python-pip
      sudo: true


    ###
    # Install Ruby+Gem
    ###
    - name: Install Ruby
      apt: name={{ item }} state=latest
      with_items:
        - ruby
        - ruby-dev
        - gem
      sudo: true
    - name: Install Gem packages
      gem: name={{ item }} user_install=no state=latest
      with_items:
        - jekyll
      sudo: true


    ###
    # Install Node+NPM
    ###
    - name: Install Node+NPM
      apt: name={{ item }} state=latest
      with_items:
        - nodejs
        - npm
      sudo: true
    - name: Install Node packages
      npm: name={{ item }} global=yes state=latest
      with_items:
        - coffee-script
        - bower
      sudo: true
    - name: Add Node to the PATH
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
      sudo: true


    ###
    # Install PHP
    ###
    - name: Install PHP
      apt: name={{ item }} state=latest
      with_items:
        - php5
        - php5-cli
        - php5-dev
        - php5-gd
        - php5-curl
        - php-apc
        - php5-intl
      sudo: true


    ##
    # Install Composer
    ##
    - name: Download composer
      shell: /usr/bin/curl -s http://getcomposer.org/installer -o /tmp/composer_installer
      sudo: true
    - name: Install composer
      shell: /usr/bin/php /tmp/composer_installer --install-dir=/usr/bin --filename=composer
      sudo: true


    ###
    # Install Apache
    ###
    - name: Install Apache
      apt: name={{ item }} state=latest
      with_items:
        - apache2
        - apache2-utils
      sudo: true
    - name: Update apache2 conf
      lineinfile: dest=/etc/apache2/apache2.conf line="" backup=yes
      sudo: true
    - name: Update apache2 conf
      lineinfile: dest=/etc/apache2/apache2.conf line="ServerTokens ProductOnly" backup=yes
      sudo: true
    - name: Update apache2 conf
      lineinfile: dest=/etc/apache2/apache2.conf line="ServerSignature Off" backup=yes
      sudo: true


    ###
    # Install mySQL
    ###
    - name: Install mySQL
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - php5-mysql
        - python-mysqldb
      sudo: true
    - name: Add remote connection
      lineinfile: dest=/etc/mysql/my.cnf regexp='^bind-address' line='#bind-address = 127.0.0.1' backup=yes
      sudo: true
    - name: Update mysql root password for all root accounts
      mysql_user: name=root password={{ mySqlRootPwd }} priv=*.*:ALL,GRANT state=present check_implicit_admin=yes login_user=root login_password={{ mySqlRootPwd }}
      sudo: true
    - name: Update mysql {{ mySqlUser }} password for all accounts
      mysql_user: name={{ mySqlUser }} password={{ mySqlUserPwd }} priv=*.*:ALL state=present login_user=root login_password={{ mySqlRootPwd }}
      sudo: true
    - name : Create DB
      mysql_db: name=website-sample state=present login_user=root login_password={{ mySqlRootPwd }}
      sudo: true
    - name: Update mysql website-sample password
      mysql_user: name={{ mySqlSampleUser }} password={{ mySqlSamplePwd }} priv=website-sample.*:ALL state=present login_user=root login_password={{ mySqlRootPwd }} host=%
      sudo: true
    - name: Restart mySQL
      service: name=mysql state=restarted
      sudo: true


    ###
    # Install Postfix
    ###
    - name: Install postfix
      apt: name=postfix state=latest
      sudo: true


    ###
    # Group Website
    ###
    - name: Create group website
      group: name=website state=present
      sudo: true


    ###
    # Install FTP ^^ (no prod EVT!!!)
    ###
    - name: Install proftpd
      apt: name=proftpd state=latest
      sudo: true
    #- name: Create ftpgroup
    #  group: name=ftpgroup-{{ user }} state=present
    #  sudo: true
    #- name: Create FTP user ftpuser-{{ user }}
    #  user: name=ftpuser-{{ user }}
    #        comment="ftpuser-{{ user }} user"
    #        group={{ item }}
    #  with_items:
    #    - ftpgroup-{{ user }}
    #  sudo: true
    - name: Add proftpd conf
      template: src={{ rootPath }}/skel/etc/proftpd/proftpd.conf.j2 dest=/etc/proftpd/proftpd.conf owner=root group=root backup=yes
      sudo: true
    - name: Restart proFTPd
      service: name=proftpd state=restarted
      sudo: true


    ###
    # Copy skell home
    ###
    - name: Add documents/website folder
      file: path=/home/{{ user }}/documents/website/website-sample/web/ state=directory
      sudo: true
    - name: Add README.md file
      template: src={{ rootPath }}/skel/home/myuser/README.md.j2 dest=/home/{{ user }}/README.md
      sudo: true
    - name: Add Apache index file
      template: src={{ rootPath }}/skel/home/myuser/documents/website/website-sample/web/index.php.j2 dest=/home/{{ user }}/documents/website/website-sample/web/index.php
      sudo: true
    - name: Clean rights for skell home
      file: path=/home/{{ user }} owner={{ user }} group={{ user }} recurse=yes
      sudo: true


    ###
    # Enable website-sample
    ###
    - name: Disable default
      shell: a2dissite 000-default
      sudo: true
    - name: Add website-sample config
      template: src={{ rootPath }}/skel/etc/apache2/sites-available/website-sample.conf.j2 dest=/etc/apache2/sites-available/website-sample.conf owner=root group=root backup=yes
      sudo: true
    - name: Enable website-sample
      shell: a2ensite website-sample
      sudo: true


    ###
    # Add phpMyAdmin
    ###
    - name: Install phpMyAdmin
      apt: name=phpmyadmin state=latest
      sudo: true
    - name: Add phpmyadmin config
      template: src={{ rootPath }}/skel/etc/apache2/sites-available/phpmyadmin.conf.j2 dest=/etc/apache2/sites-available/phpmyadmin.conf owner=root group=root backup=yes
      sudo: true
    - name: Add folder
      file: path=/home/{{ user }}/documents/website/phpmyadmin/ state=directory
      sudo: true
    - name: Add link to www folder
      file: src=/usr/share/phpmyadmin dest=/home/{{ user }}/documents/website/phpmyadmin/web state=link
      sudo: true
    - name: Enable phpmyadmin
      shell: a2ensite phpmyadmin
      sudo: true


    ###
    # Add APC Monitoring
    ###
    - name: Add APC Monitoring config
      template: src={{ rootPath }}/skel/etc/apache2/sites-available/apc-monitor.conf.j2 dest=/etc/apache2/sites-available/apc-monitor.conf owner=root group=root backup=yes
      sudo: true
    - name: Add folder
      file: path=/home/{{ user }}/documents/website/apc-monitor/ state=directory
      sudo: true
    - name: Add Git repo
      git: repo=https://github.com/Remiii/apc-monitor.git dest=/home/{{ user }}/documents/website/apc-monitor/
      sudo: true
    - name: Enable phpmyadmin
      shell: a2ensite apc-monitor
      sudo: true


    ###
    # Apache2 config
    ###
    - name: Apache2 php config
      lineinfile: dest=/etc/php5/apache2/php.ini regexp='^memory_limit = 128M' line='memory_limit = 256M' backup=yes
      sudo: true
    - name: Apache2 module
      apache2_module: state=present name={{ item }}
      with_items:
        - headers
        - rewrite
      sudo: true


    ###
    # Restart Service
    ###
    - name: Restart Apache
      service: name=apache2 state=restarted
      sudo: true
    - name: Restart SSHd
      service: name=ssh state=restarted
      sudo: true
    - name: Restart mySQL
      service: name=mysql state=restarted
      sudo: true
    - name: Restart proFTPd
      service: name=proftpd state=restarted
      sudo: true


    ###
    # CUSTOM for your Server
    ###
    # TBD


    ###
    # Alert
    ###
    #- name: Alert on IRC
    #  irc: server={{ ircServer }} channel="#{{ ircChannel }}" msg="Ansible: deploy ubuntu simple Symfony App"


